name: my-ci-flow
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-html

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@latest

      - name: Run API test_articles.py
        run: python -m unittest tests.test_api.test_articles.TestArticles.test_article_status

      - name: Run UI test_login.py
        run: python -m unittest tests.test_web.test_log_in_page.Login_Page_Test.test_run

      - name: Run tests with pytest and generate report
        run: |
            pytest tests/test_api/api_test_runner.py --html=report_api.html
            pytest tests/test_web/test_log_in_page.py --html=report_ui.html
          

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports
          path: ./*.html

      - name: Notify Slack on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: C06Q6FRSFKJ
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: 'Test Failed: ${{ github.run_id }}'
          SLACK_TITLE: 'Test Execution Failed'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'

      - name: Notify Slack on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: C06Q6FRSFKJ
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: 'Test Succeeded: ${{ github.run_id }}'
          SLACK_TITLE: 'Test Execution Succeeded'
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'